"""Core data structures for the travel-behaviour ABM."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class Activity:
    """An activity that anchors travel demand.

    Attributes:
        type: Activity type (e.g., home, work, leisure).
        subtype: Optional segment label for activity stratification.
        planned_source: "organic" or recommender name for leisure activities.
        accepted_recommendation: Whether the leisure recommendation was accepted.
        recommended_place_id: Place id used when recommendation was accepted.
        start_time: Scheduled start time in minutes from 0.
        duration: Planned duration in minutes.
        location: (x, y) grid location.
        is_mandatory: Whether the activity is mandatory (e.g., work, home).
    """

    type: str
    subtype: str
    planned_source: str
    accepted_recommendation: bool
    recommended_place_id: str
    start_time: int
    duration: int
    location: tuple
    is_mandatory: bool = False


@dataclass
class Trip:
    """A realized trip generated by the simulation.

    Attributes:
        agent_id: Traveler identifier.
        origin: Origin location (x, y).
        destination: Destination location (x, y).
        depart_time: Departure time in minutes.
        mode: Chosen travel mode.
        purpose: Activity type the trip is serving.
        purpose_subtype: Optional subtype of purpose (for segmented leisure).
        recommendation_source: Recommender source used for planned destination.
        accepted_recommendation: Whether recommendation was accepted.
        eta_acceptance: Dynamic willingness-to-accept parameter used for decision.
        recommended_place_id: Place id used by recommender.
        user_feedback_like: User feedback on recommended place (1 like, 0 dislike, -1 not applicable).
        distance_km: Manhattan distance in kilometers.
        travel_time_min: Actual travel time in minutes.
        cost: Monetary cost in dollars.
        emissions_g: CO2e grams.
        utility: Total utility (travel utility + activity utility).
        travel_utility: Utility component of travel itself.
        activity_utility: Utility component of destination activity.
        arrival_time: Arrival time in minutes.
    """

    agent_id: int
    origin: tuple
    destination: tuple
    depart_time: int
    mode: str
    purpose: str
    purpose_subtype: str
    recommendation_source: str
    accepted_recommendation: bool
    eta_acceptance: float
    recommended_place_id: str
    user_feedback_like: int
    distance_km: float
    travel_time_min: int
    cost: float
    emissions_g: float
    utility: float
    travel_utility: float
    activity_utility: float
    arrival_time: int
